[build]
publish = "public"
command = "hugo --gc"

[context.production.environment]
HUGO_VERSION = "0.59.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.59.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.59.0"

[context.branch-deploy]
command = "hugo --gc -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.59.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"


